server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
   gateway:
     routes:
       - id: user-service
         uri:  lb://USER-SERVICE
         predicates:
           - Path=/user-service/**
         filters:
           - StripPrefix=1
       - id: vehicle-service
         uri: lb://VEHICLE-SERVICE
         predicates:
           - Path=/vehicle-service/**
         filters:
           - StripPrefix=1
       - id: parking-space-service
         uri: lb://PARKING-SPACE-SERVICE
         predicates:
           - Path=/parking-space-service/**
         filters:
           - StripPrefix=1
       - id: payment-service
         uri: lb://PAYMENT-SERVICE
         predicates:
           - Path=/payment-service/**
         filters:
           - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


