server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
   gateway:
     routes:
       -id: user-service
       uri: lb://USER-SERVICE
       predicates:
         -Path=/user-service/**
       filters:
         - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


