server:
  port: 8084

spring:
  application:
    name: parking-space-service

logging:
  level:
    lk.ijse.parkingspaceservice: DEBUG


app:
  parking:
    max-spaces-per-owner: 50
    default-hourly-rate: 100.00
    booking-timeout-minutes: 15