server:
  port: 8083

spring:
  application:
    name: vehicle-service

logging:
  level:
    lk.ijse.vehicleservice: DEBUG


app:
  vehicle:
    max-vehicles-per-user: 5
    allowed-vehicle-types: ["CAR", "MOTORCYCLE", "VAN"]